// File storage behind a three-function interface: put, get, delete by key.
//
// Two backends, chosen by configuration rather than by build:
//
//   local  writes under STORAGE_DIR. The default, and what development uses.
//   s3     any S3-compatible bucket — Cloudflare R2, AWS S3, Backblaze B2.
//
// The local backend cannot be used on a managed platform. Those filesystems are
// ephemeral, so an uploaded resume survives until the next deploy and no
// further, and with more than one instance each holds different files. A
// production write without a bucket therefore fails loudly (see assertWritable)
// rather than appearing to succeed.
import { mkdir, writeFile, readFile, unlink } from "fs/promises";
import { join, dirname } from "path";
import {
  S3Client,
  PutObjectCommand,
  GetObjectCommand,
  DeleteObjectCommand,
} from "@aws-sdk/client-s3";

const STORAGE_ROOT = process.env.STORAGE_DIR ?? "./.storage";
const BUCKET = process.env.STORAGE_BUCKET;

export const SOURCE_FILE_MAX_BYTES = 10 * 1024 * 1024; // 10 MB
export const PROOF_FILE_MAX_BYTES = 15 * 1024 * 1024; // 15 MB
export const TEXT_EXCERPT_MAX_CHARS = 120_000;

export function sanitizeFilename(name: string): string {
  const base = name.replace(/[\\/]/g, "_").replace(/[^a-zA-Z0-9._-]/g, "_");
  return base.slice(-180) || "file";
}

export function makeStorageKey(
  scope: "sources" | "proof" | "resumes",
  id: string,
  filename: string
): string {
  return `${scope}/${id}/${sanitizeFilename(filename)}`;
}

const TEXT_LIKE_EXTENSIONS = [".txt", ".md", ".csv", ".json", ".log"];

export function isTextLike(filename: string): boolean {
  const lower = filename.toLowerCase();
  return TEXT_LIKE_EXTENSIONS.some((ext) => lower.endsWith(ext));
}

export function extractTextExcerpt(bytes: Buffer): string {
  return bytes.toString("utf-8").slice(0, TEXT_EXCERPT_MAX_CHARS);
}

// --- backend selection --------------------------------------------------------

export type StorageBackend = "local" | "s3";

export function storageBackend(): StorageBackend {
  return BUCKET ? "s3" : "local";
}

// Refuses to write rather than refusing to start.
//
// A deployment that stores files on an ephemeral disk looks fine until someone
// needs the file back, which is the worst possible moment to find out — so a
// production write without a bucket fails immediately and says why. The check
// is not at module load because `next build` runs with NODE_ENV=production and
// no runtime configuration, and a build should not fail for the absence of a
// value it was never going to have.
function assertWritable(): void {
  if (process.env.NODE_ENV === "production" && !BUCKET) {
    throw new Error(
      "STORAGE_BUCKET is not set. Uploads need S3-compatible storage in production; " +
        "the local filesystem does not persist on a managed platform."
    );
  }
}

let s3: S3Client | null = null;

function client(): S3Client {
  if (!s3) {
    s3 = new S3Client({
      // R2 and most S3-compatible providers need an explicit endpoint; AWS S3
      // does not, and infers it from the region.
      endpoint: process.env.STORAGE_ENDPOINT,
      region: process.env.STORAGE_REGION ?? "auto",
      credentials:
        process.env.STORAGE_ACCESS_KEY_ID && process.env.STORAGE_SECRET_ACCESS_KEY
          ? {
              accessKeyId: process.env.STORAGE_ACCESS_KEY_ID,
              secretAccessKey: process.env.STORAGE_SECRET_ACCESS_KEY,
            }
          : undefined,
    });
  }
  return s3;
}

// --- local ---------------------------------------------------------------------

function resolvePath(key: string): string {
  // Keys are generated by makeStorageKey and never user-supplied, but guard
  // against traversal regardless.
  const safe = key.replace(/\.\./g, "");
  return join(/* turbopackIgnore: true */ STORAGE_ROOT, safe);
}

// --- public interface ----------------------------------------------------------

export async function putObject(key: string, bytes: Buffer): Promise<void> {
  assertWritable();
  if (storageBackend() === "s3") {
    await client().send(new PutObjectCommand({ Bucket: BUCKET, Key: key, Body: bytes }));
    return;
  }
  const path = resolvePath(key);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, bytes);
}

export async function getObject(key: string): Promise<Buffer | null> {
  if (storageBackend() === "s3") {
    try {
      const res = await client().send(new GetObjectCommand({ Bucket: BUCKET, Key: key }));
      const bytes = await res.Body?.transformToByteArray();
      return bytes ? Buffer.from(bytes) : null;
    } catch {
      // A missing object is a null, not an error: callers already handle "no
      // file on record" and should not have to tell the two apart.
      return null;
    }
  }
  try {
    return await readFile(resolvePath(key));
  } catch {
    return null;
  }
}

export async function deleteObject(key: string): Promise<void> {
  if (storageBackend() === "s3") {
    try {
      await client().send(new DeleteObjectCommand({ Bucket: BUCKET, Key: key }));
    } catch {
      // already gone — deletes are idempotent
    }
    return;
  }
  try {
    await unlink(resolvePath(key));
  } catch {
    // already gone — deletes are idempotent
  }
}
