// File storage behind an R2-shaped interface (put/get/delete by key).
// Locally this writes to disk under STORAGE_DIR. In a Cloudflare deployment,
// swap this module's implementation for an R2 bucket binding
// (`env.SOURCES_BUCKET.put/get/delete`) — the call sites in this app only
// use the three functions exported below, so the swap is contained here.
import { mkdir, writeFile, readFile, unlink } from "fs/promises";
import { join, dirname } from "path";

const STORAGE_ROOT = process.env.STORAGE_DIR ?? "./.storage";

export const SOURCE_FILE_MAX_BYTES = 10 * 1024 * 1024; // 10 MB
export const PROOF_FILE_MAX_BYTES = 15 * 1024 * 1024; // 15 MB
export const TEXT_EXCERPT_MAX_CHARS = 120_000;

export function sanitizeFilename(name: string): string {
  const base = name.replace(/[\\/]/g, "_").replace(/[^a-zA-Z0-9._-]/g, "_");
  return base.slice(-180) || "file";
}

function resolvePath(key: string): string {
  // Keys are generated by this module (never user-supplied paths), but guard
  // against path traversal regardless. STORAGE_ROOT is env-driven, which
  // Turbopack can't statically scope for output tracing — this whole
  // function only runs in local dev (see module doc comment above), so the
  // trace warning is silenced rather than "fixed" by pinning a static path.
  const safe = key.replace(/\.\./g, "");
  return join(/* turbopackIgnore: true */ STORAGE_ROOT, safe);
}

export async function putObject(key: string, bytes: Buffer): Promise<void> {
  const path = resolvePath(key);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, bytes);
}

export async function getObject(key: string): Promise<Buffer | null> {
  try {
    return await readFile(resolvePath(key));
  } catch {
    return null;
  }
}

export async function deleteObject(key: string): Promise<void> {
  try {
    await unlink(resolvePath(key));
  } catch {
    // already gone — deletes are idempotent
  }
}

export function makeStorageKey(scope: "sources" | "proof" | "resumes", id: string, filename: string): string {
  return `${scope}/${id}/${sanitizeFilename(filename)}`;
}

const TEXT_LIKE_EXTENSIONS = [".txt", ".md", ".csv", ".json", ".log"];

export function isTextLike(filename: string): boolean {
  const lower = filename.toLowerCase();
  return TEXT_LIKE_EXTENSIONS.some((ext) => lower.endsWith(ext));
}

export function extractTextExcerpt(bytes: Buffer): string {
  return bytes.toString("utf-8").slice(0, TEXT_EXCERPT_MAX_CHARS);
}
